name: Continuous integration


on:
  push:
    branches:
      - main
      - dev


permissions:
  contents: write


jobs:
  build:
    strategy:
      matrix:
        config: 
          - { os: windows-latest, image: "", artifact-name: Windows, additional-command: "", cmake-parameters: "", upload-path: build/install-dir/bin/* }
          - { os: ubuntu-latest, image: ghcr.io/lazypanda07/ubuntu_cxx20:24.04, artifact-name: Linux, additional-command: "sudo apt update && sudo apt install -y libasound2-dev", cmake-parameters: "", upload-path: build/install-dir/bin/* }
          - { os: windows-latest, image: "", artifact-name: WindowsClientLibrary, additional-command: "", cmake-parameters: "-DBUILD_CLIENT=OFF -DBUILD_SERVER=OFF", upload-path: build/install-dir/bin/*.dll }
          - { os: ubuntu-latest, image: ghcr.io/lazypanda07/ubuntu_cxx20:24.04, artifact-name: LinuxClientLibrary, additional-command: "sudo apt update && sudo apt install -y libasound2-dev", cmake-parameters: "-DBUILD_CLIENT=OFF -DBUILD_SERVER=OFF", upload-path: build/install-dir/lib/*.so }
    runs-on: ${{ matrix.config.os }}
    container:
      image: ${{ matrix.config.image }}

    steps:
    - uses: actions/checkout@v6
      
    - name: Enable NMake
      if: ${{ matrix.config.os == 'windows-latest' }}
      uses: ilammy/msvc-dev-cmd@v1.13.0

    - name: Additional action
      if: ${{ matrix.config.additional-command != '' }}
      run: ${{ matrix.config.additional-command }}

    - name: Build
      run: |
        mkdir build
        cd build
        cmake -DCMAKE_INSTALL_PREFIX=install-dir -DCMAKE_BUILD_TYPE=Release ${{ matrix.config.cmake-parameters }} -G "Ninja" ..
        cmake --build . -j
        cmake --install .

    - name: Upload ${{ matrix.config.artifact-name }}
      uses: actions/upload-artifact@v6
      with:
        name: ${{ matrix.config.artifact-name }}
        path: ${{ matrix.config.upload-path }}
        

  publish:
    needs: 
      - build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v6

    - name: Get current branch
      uses : LazyPanda07/extract-current-branch@master

    - name: Setup release version variable
      shell: pwsh
      run: echo "VERSION=$($($($(Select-String -Path .\DiscordCloneClientLibrary\src\Functionality.cpp -Pattern version) -split '( = )')[3].TrimEnd(';')).Trim('\"'))" >> $Env:GITHUB_ENV

    - uses: actions/download-artifact@v7

    - name: Create Windows and Linux zips
      run: |
        zip -r windows.zip Windows
        zip -r linux.zip Linux
        zip -r linux_client_library.zip LinuxClientLibrary
        zip -r windows_client_library.zip WindowsClientLibrary

    - name: Publish
      if: ${{ env.CURRENT_BRANCH == 'main' }}
      run: gh release create v${{ env.VERSION }} *.zip --title v${{ env.VERSION }} --generate-notes
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
