name: Continuous integration


on:
  push:
    branches:
      - main
      - dev


permissions:
  contents: write


jobs:
  windows-client-build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v6
  
    - name: Enable CL
      uses: ilammy/msvc-dev-cmd@v1.13.0

    - name: Build
      run: |
        mkdir build
        cd build
        cmake -DCMAKE_BUILD_TYPE=MinSizeRel -DCMAKE_INSTALL_PREFIX=install-dir -DBUILD_SERVER=OFF -G "Ninja" ..
        cmake --build . -j
        cmake --install .

    - name: Copy binaries
      shell: bash
      run: |
        mkdir out
        mv build/install-dir/bin/* out

    - name: Upload Windows client
      uses: actions/upload-artifact@v7
      with:
        name: windows_client
        path: out/*


  windows-server-build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v6
  
    - name: Enable CL
      uses: ilammy/msvc-dev-cmd@v1.13.0

    - name: Build
      run: |
        mkdir build
        cd build
        cmake -DCMAKE_BUILD_TYPE=MinSizeRel -DCMAKE_INSTALL_PREFIX=install-dir -DBUILD_CLIENT=OFF -DBUILD_CLIENT_LIBRARY=OFF -G "Ninja" ..
        cmake --build . -j
        cmake --install .
        
    - name: Copy binaries
      shell: bash
      run: |
        mkdir out
        mv build/install-dir/bin/* out

    - name: Upload Windows server
      uses: actions/upload-artifact@v7
      with:
        name: windows_server
        path: out/*
  

  windows-client-library-build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v6
  
    - name: Enable CL
      uses: ilammy/msvc-dev-cmd@v1.13.0

    - name: Build
      run: |
        mkdir build
        cd build
        cmake -DCMAKE_BUILD_TYPE=MinSizeRel -DCMAKE_INSTALL_PREFIX=install-dir -DBUILD_CLIENT=OFF -DBUILD_SERVER=OFF -DBUILD_CLIENT_LIBRARY=ON -DBUILD_SHARED_CLIENT_LIBRARY=ON -G "Ninja" ..
        cmake --build . -j
        cmake --install .

    - name: Copy binaries
      shell: bash
      run: |
        mkdir out
        mkdir out/include
        mv build/install-dir/bin/* out
        mv DiscordCloneClientLibrary/include/c_api.h out/include

    - name: Upload Windows client library
      uses: actions/upload-artifact@v7
      with:
        name: windows_client_library
        path: out/*


  linux-client-build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/lazypanda07/ubuntu_cxx20:24.04

    steps:
    - uses: actions/checkout@v6
  
    - name: Install dependencies
      run: |
        sudo apt update 
        sudo apt install -y libasound2-dev

    - name: Build
      run: |
        mkdir build
        cd build
        cmake -DCMAKE_BUILD_TYPE=MinSizeRel -DCMAKE_INSTALL_PREFIX=install-dir -DBUILD_SERVER=OFF -G "Ninja" ..
        cmake --build . -j
        cmake --build . --target install/strip

    - name: Copy binaries
      run: |
        mkdir out
        mv build/install-dir/bin/* out

    - name: Upload Linux client
      uses: actions/upload-artifact@v7
      with:
        name: linux_client
        path: out/*


  linux-server-build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/lazypanda07/ubuntu_cxx20:24.04

    steps:
    - uses: actions/checkout@v6
  
    - name: Install dependencies
      run: |
        sudo apt update 
        sudo apt install -y libasound2-dev

    - name: Build
      run: |
        mkdir build
        cd build
        cmake -DCMAKE_BUILD_TYPE=MinSizeRel -DCMAKE_INSTALL_PREFIX=install-dir -DBUILD_CLIENT=OFF -DBUILD_CLIENT_LIBRARY=OFF -G "Ninja" ..
        cmake --build . -j
        cmake --build . --target install/strip

    - name: Copy binaries
      run: |
        mkdir out
        mv build/install-dir/bin/* out

    - name: Upload Linux server
      uses: actions/upload-artifact@v7
      with:
        name: linux_server
        path: out/*
  

  linux-client-library-build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/lazypanda07/ubuntu_cxx20:24.04

    steps:
    - uses: actions/checkout@v6
  
    - name: Install dependencies
      run: |
        sudo apt update 
        sudo apt install -y libasound2-dev

    - name: Build
      run: |
        mkdir build
        cd build
        cmake -DCMAKE_BUILD_TYPE=MinSizeRel -DCMAKE_INSTALL_PREFIX=install-dir -DBUILD_CLIENT=OFF -DBUILD_SERVER=OFF -DBUILD_CLIENT_LIBRARY=ON -DBUILD_SHARED_CLIENT_LIBRARY=ON -G "Ninja" ..
        cmake --build . -j
        cmake --install .

    - name: Copy binaries
      run: |
        mkdir out
        mkdir out/include
        mv build/install-dir/lib/*.so out
        mv DiscordCloneClientLibrary/include/c_api.h out/include

    - name: Upload Linux client library
      uses: actions/upload-artifact@v7
      with:
        name: linux_client_library
        path: out/*

        
  publish:
    runs-on: ubuntu-latest
    needs: 
      - windows-client-build
      - windows-server-build
      - windows-client-library-build
      - linux-client-build
      - linux-server-build
      - linux-client-library-build 

    steps:
    - uses: actions/checkout@v6

    - name: Get current branch
      uses : LazyPanda07/extract-current-branch@master

    - name: Setup release version variable
      shell: pwsh
      run: echo "VERSION=$($($($(Select-String -Path .\DiscordCloneClientLibrary\src\Functionality.cpp -Pattern version) -split '( = )')[3].TrimEnd(';')).Trim('\"'))" >> $Env:GITHUB_ENV

    - uses: actions/download-artifact@v7

    - name: Create Windows and Linux zips
      run: |
        zip -r windows.zip windows_client/*
        zip -r windows_server.zip windows_server/*
        zip -r windows_client_library.zip windows_client_library/*
        zip -r linux.zip linux_client/*
        zip -r linux_server.zip linux_server/*
        zip -r linux_client_library.zip linux_client_library/*

    - name: Publish
      if: ${{ env.CURRENT_BRANCH == 'main' }}
      run: gh release create v${{ env.VERSION }} *.zip --title v${{ env.VERSION }} --generate-notes
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
